wandb_version: 1

_n_gpu:
  desc: null
  value: 1
_name_or_path:
  desc: null
  value: allenai/led-base-16384
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: train/global_step
      6:
      - 3
    python_version: 3.8.13
    start_time: 1655313614
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 1
      - 7
      - 13
      4: 3.8.13
      5: 0.12.17
      6: 4.19.2
      8:
      - 5
activation_dropout:
  desc: null
  value: 0.0
activation_function:
  desc: null
  value: gelu
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - LEDForConditionalGeneration
attention_dropout:
  desc: null
  value: 0.0
attention_window:
  desc: null
  value:
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
  - 1024
auto_find_batch_size:
  desc: null
  value: false
bad_words_ids:
  desc: null
  value: null
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
bos_token_id:
  desc: null
  value: 0
chunk_size_feed_forward:
  desc: null
  value: 0
classif_dropout:
  desc: null
  value: 0.0
classifier_dropout:
  desc: null
  value: 0.0
cross_attention_hidden_size:
  desc: null
  value: null
d_model:
  desc: null
  value: 768
data_seed:
  desc: null
  value: None
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_bucket_cap_mb:
  desc: null
  value: None
ddp_find_unused_parameters:
  desc: null
  value: None
debug:
  desc: null
  value: '[]'
decoder_attention_heads:
  desc: null
  value: 12
decoder_ffn_dim:
  desc: null
  value: 3072
decoder_layerdrop:
  desc: null
  value: 0.0
decoder_layers:
  desc: null
  value: 6
decoder_start_token_id:
  desc: null
  value: 2
deepspeed:
  desc: null
  value: None
disable_tqdm:
  desc: null
  value: false
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: false
dropout:
  desc: null
  value: 0.1
early_stopping:
  desc: null
  value: true
encoder_attention_heads:
  desc: null
  value: 12
encoder_ffn_dim:
  desc: null
  value: 3072
encoder_layerdrop:
  desc: null
  value: 0.0
encoder_layers:
  desc: null
  value: 6
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: 2
eval_accumulation_steps:
  desc: null
  value: None
eval_batch_size:
  desc: null
  value: 3
eval_delay:
  desc: null
  value: 0
eval_steps:
  desc: null
  value: 100
evaluation_strategy:
  desc: null
  value: steps
exponential_decay_length_penalty:
  desc: null
  value: null
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: true
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
fsdp:
  desc: null
  value: '[]'
fsdp_min_num_params:
  desc: null
  value: 0
full_determinism:
  desc: null
  value: false
generation_max_length:
  desc: null
  value: None
generation_num_beams:
  desc: null
  value: None
gradient_accumulation_steps:
  desc: null
  value: 4
gradient_checkpointing:
  desc: null
  value: false
greater_is_better:
  desc: null
  value: None
group_by_length:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: amp
hub_model_id:
  desc: null
  value: None
hub_private_repo:
  desc: null
  value: false
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
    '2': LABEL_2
ignore_data_skip:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
init_std:
  desc: null
  value: 0.02
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: true
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
    LABEL_2: 2
label_names:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
learning_rate:
  desc: null
  value: 5.0e-05
length_column_name:
  desc: null
  value: length
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
log_level:
  desc: null
  value: -1
log_level_replica:
  desc: null
  value: -1
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ../../models/runs/Jun15_13-19-58_gn-0017
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 5
logging_strategy:
  desc: null
  value: steps
lr_scheduler_type:
  desc: null
  value: linear
max_decoder_position_embeddings:
  desc: null
  value: 1024
max_encoder_position_embeddings:
  desc: null
  value: 16384
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 512
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: None
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: led
mp_parameters:
  desc: null
  value: ''
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 2
num_hidden_layers:
  desc: null
  value: 6
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 3.0
optim:
  desc: null
  value: adamw_hf
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: ../../models/
output_hidden_states:
  desc: null
  value: false
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: false
pad_token_id:
  desc: null
  value: 1
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 8
per_device_train_batch_size:
  desc: null
  value: 8
per_gpu_eval_batch_size:
  desc: null
  value: 3
per_gpu_train_batch_size:
  desc: null
  value: 3
predict_with_generate:
  desc: null
  value: true
prediction_loss_only:
  desc: null
  value: false
prefix:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: None
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value: '[''tensorboard'', ''wandb'']'
resume_from_checkpoint:
  desc: null
  value: None
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
run_name:
  desc: null
  value: ../../models/
save_on_each_node:
  desc: null
  value: false
save_steps:
  desc: null
  value: 100
save_strategy:
  desc: null
  value: steps
save_total_limit:
  desc: null
  value: 2
seed:
  desc: null
  value: 42
sep_token_id:
  desc: null
  value: null
sharded_ddp:
  desc: null
  value: '[]'
skip_memory_metrics:
  desc: null
  value: true
sortish_sampler:
  desc: null
  value: false
task_specific_params:
  desc: null
  value: null
temperature:
  desc: null
  value: 1.0
tf32:
  desc: null
  value: None
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: true
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torch_dtype:
  desc: null
  value: null
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 3
transformers_version:
  desc: null
  value: 4.19.2
typical_p:
  desc: null
  value: 1.0
use_bfloat16:
  desc: null
  value: false
use_cache:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
vocab_size:
  desc: null
  value: 50267
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
xpu_backend:
  desc: null
  value: None
